const restaurantMenuData = [
  {
    id: "238086",
    name: "Chinese Chef Co",
    cuisines: ["Chinese", "Fast Food", "Asian"],
    rating: 3.7,
    costForTwo: 300,
    offers: ["₹125 OFF on orders above ₹249"],
    menu: [
      { id: "101", name: "Veg Hakka Noodles", price: 180 },
      { id: "102", name: "Veg Manchurian", price: 200 },
      { id: "103", name: "Veg Fried Rice", price: 170 },
      { id: "104", name: "Schezwan Rice", price: 190 },
      { id: "105", name: "Spring Rolls", price: 150 },
      { id: "106", name: "Crispy Corn", price: 160 },
      { id: "107", name: "Chilli Paneer", price: 220 },
      { id: "108", name: "Paneer Noodles", price: 210 },
      { id: "109", name: "Veg Manchow Soup", price: 130 },
      { id: "110", name: "Garlic Noodles", price: 195 },
    ],
  },

  {
    id: "220133",
    name: "Blue Dragon Chinese Katta",
    cuisines: ["Chinese"],
    rating: 4.3,
    costForTwo: 200,
    offers: ["Free Delivery above ₹199"],
    menu: [
      { id: "201", name: "Chicken Noodles", price: 220 },
      { id: "202", name: "Egg Fried Rice", price: 180 },
      { id: "203", name: "Chicken Manchurian", price: 240 },
      { id: "204", name: "Chilli Chicken", price: 260 },
      { id: "205", name: "Chicken Soup", price: 150 },
      { id: "206", name: "Chicken Spring Rolls", price: 190 },
      { id: "207", name: "Garlic Chicken", price: 270 },
      { id: "208", name: "Chicken Schezwan Rice", price: 230 },
      { id: "209", name: "Chicken Lollipop", price: 280 },
      { id: "210", name: "Chicken Momos", price: 200 },
    ],
  },

  {
    id: "482340",
    name: "Ching's Essence",
    cuisines: ["Chinese", "North Indian"],
    rating: 4.1,
    costForTwo: 200,
    offers: ["10% OFF on orders above ₹299"],
    menu: [
      { id: "301", name: "Paneer Fried Rice", price: 190 },
      { id: "302", name: "Veg Noodles", price: 170 },
      { id: "303", name: "Paneer Chilli", price: 220 },
      { id: "304", name: "Dal Fry", price: 180 },
      { id: "305", name: "Jeera Rice", price: 160 },
      { id: "306", name: "Butter Roti", price: 35 },
      { id: "307", name: "Veg Manchow Soup", price: 130 },
      { id: "308", name: "Paneer Butter Masala", price: 260 },
      { id: "309", name: "Veg Schezwan Rice", price: 200 },
      { id: "310", name: "Plain Rice", price: 140 },
    ],
  },

  {
    id: "464690",
    name: "Lallantop Dhaba Bar",
    cuisines: ["Tandoor", "Pastas", "Pizzas"],
    rating: 3.8,
    costForTwo: 800,
    offers: ["20% OFF up to ₹100"],
    menu: [
      { id: "401", name: "Paneer Tikka", price: 320 },
      { id: "402", name: "Butter Chicken", price: 420 },
      { id: "403", name: "Dal Makhani", price: 260 },
      { id: "404", name: "Butter Naan", price: 60 },
      { id: "405", name: "Tandoori Roti", price: 40 },
      { id: "406", name: "Chicken Tikka", price: 380 },
      { id: "407", name: "Veg Kolhapuri", price: 240 },
      { id: "408", name: "Jeera Rice", price: 180 },
      { id: "409", name: "Paneer Butter Masala", price: 280 },
      { id: "410", name: "Gulab Jamun", price: 120 },
    ],
  },

  {
    id: "47314",
    name: "Raje Chinese",
    cuisines: ["Chinese"],
    rating: 4.0,
    costForTwo: 400,
    offers: ["Flat ₹50 OFF"],
    menu: [
      { id: "501", name: "Egg Noodles", price: 200 },
      { id: "502", name: "Chicken Fried Rice", price: 230 },
      { id: "503", name: "Veg Manchurian", price: 190 },
      { id: "504", name: "Chicken Manchurian", price: 260 },
      { id: "505", name: "Chilli Chicken", price: 270 },
      { id: "506", name: "Veg Spring Rolls", price: 160 },
      { id: "507", name: "Chicken Schezwan Noodles", price: 240 },
      { id: "508", name: "Chicken Soup", price: 150 },
      { id: "509", name: "Chicken Lollipop", price: 290 },
      { id: "510", name: "Chicken Momos", price: 210 },
    ],
  },

  {
    id: "228565",
    name: "Subhanallah Biryani House",
    cuisines: ["Biryani", "Chinese", "North Indian", "Mughlai"],
    rating: 3.7,
    costForTwo: 200,
    offers: ["20% OFF up to ₹50"],
    menu: [
      { id: "601", name: "Chicken Biryani", price: 250 },
      { id: "602", name: "Veg Biryani", price: 180 },
      { id: "603", name: "Chicken Fried Rice", price: 220 },
      { id: "604", name: "Egg Fried Rice", price: 200 },
      { id: "605", name: "Chicken Kebab", price: 260 },
      { id: "606", name: "Chicken Curry", price: 240 },
      { id: "607", name: "Butter Roti", price: 35 },
      { id: "608", name: "Dal Tadka", price: 180 },
      { id: "609", name: "Chicken Manchurian", price: 260 },
      { id: "610", name: "Sweet Lassi", price: 90 },
    ],
  },

  {
    id: "229286",
    name: "Mandarin Oak – The Heavenly Chinese",
    cuisines: ["Chinese", "Oriental", "Pan-Asian", "Snacks"],
    rating: 4.0,
    costForTwo: 350,
    offers: ["Free Dessert on orders above ₹499"],
    menu: [
      { id: "701", name: "Veg Dimsums", price: 210 },
      { id: "702", name: "Chicken Dimsums", price: 240 },
      { id: "703", name: "Kung Pao Chicken", price: 280 },
      { id: "704", name: "Veg Pad Thai", price: 260 },
      { id: "705", name: "Chicken Pad Thai", price: 290 },
      { id: "706", name: "Crispy Lotus Stem", price: 220 },
      { id: "707", name: "Veg Fried Rice", price: 190 },
      { id: "708", name: "Chicken Fried Rice", price: 230 },
      { id: "709", name: "Hot & Sour Soup", price: 160 },
      { id: "710", name: "Chocolate Brownie", price: 140 },
    ],
  },
];

export default restaurantMenuData;
